name: Build, test and push Docker Images

on:
  pull_request:
    paths:
      - ".github/workflows/docker.yml"
      # We use local reusable workflows to make architecture clean an simple
      # https://docs.github.com/en/actions/using-workflows/reusing-workflows
      - ".github/workflows/docker-build-test-upload.yml"
      - ".github/workflows/docker-tag-manifest-push.yml"
      - ".github/workflows/docker-wiki-update.yml"

      # We use local composite actions to combine multiple workflow steps within one action
      # https://docs.github.com/en/actions/creating-actions/about-custom-actions#composite-actions
      - ".github/actions/create-dev-env/action.yml"
      - ".github/actions/download-manifests/action.yml"
      - ".github/actions/load-image/action.yml"

      - "base-notebook/**"
      - "minimal-notebook/**"
      - "scipy-notebook/**"

      - "tagging/**"
      - "tests/**"
      - "requirements-dev.txt"
  push:
    branches:
      - gpu-x86
    paths:
      - ".github/workflows/docker.yml"
      - ".github/workflows/docker-build-test-upload.yml"
      - ".github/workflows/docker-tag-manifest-push.yml"
      - ".github/workflows/docker-wiki-update.yml"

      - ".github/actions/create-dev-env/action.yml"
      - ".github/actions/download-manifests/action.yml"
      - ".github/actions/load-image/action.yml"

      - "base-notebook/**"
      - "minimal-notebook/**"
      - "scipy-notebook/**"

      - "tagging/**"
      - "tests/**"
      - "requirements-dev.txt"
  workflow_dispatch:

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  # only cancel in-progress jobs or runs for the current workflow - matches against branch & tags
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  amd64-base:
    uses: ./.github/workflows/docker-build-test-upload.yml
    with:
      parentImage: ""
      image: base-notebook
      platform: amd64
      runsOn: ubuntu-latest

  amd64-minimal:
    needs: [amd64-base]
    uses: ./.github/workflows/docker-build-test-upload.yml
    with:
      parentImage: base-notebook
      image: minimal-notebook
      platform: amd64
      runsOn: ubuntu-latest

  amd64-scipy:
    needs: [amd64-minimal]
    uses: ./.github/workflows/docker-build-test-upload.yml
    with:
      parentImage: minimal-notebook
      image: scipy-notebook
      platform: amd64
      runsOn: ubuntu-latest

  amd64-images-tag-push:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    needs:
      [
        amd64-base,
        amd64-minimal,
        amd64-scipy,
      ]
    uses: ./.github/workflows/docker-tag-manifest-push.yml
    with:
      platform: amd64
      runsOn: ubuntu-latest
      images: >-
        [
          "base-notebook",
          "minimal-notebook",
          "scipy-notebook",
        ]

  wiki-update:
    permissions:
      contents: write
    needs: [amd64-images-tag-push]
    uses: ./.github/workflows/docker-wiki-update.yml
